# Generated by Django 3.1.5 on 2021-01-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210131_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phoned',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='special_files',
        ),
    ]
