# Generated by Django 3.1.5 on 2021-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210131_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Zoom', 'Zoom'), ('Facebook', 'Facebook')], default='', max_length=100),
        ),
    ]
